In [1]:
import torch
import ModelToys
model = ModelToys.LinearModel()

"""
data = 1, 2, 3, 4, 5
label = 2, 4, 6, 8, 10
"""

# reference : https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

'\ndata = 1, 2, 3, 4, 5\nlabel = 2, 4, 6, 8, 10\n'

In [53]:
data = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float32, requires_grad=True)
data = data.view([6, 1])
labels = torch.tensor([2, 4, 6, 8, 10, 12], dtype=torch.float32)
labels = labels.view([6, 1])
print(data)
print(labels)

prediction = model.forward(data)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]], grad_fn=<ViewBackward0>)
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.]])


In [54]:
# forward
prediction

tensor([[-0.4403],
        [-1.3351],
        [-2.2299],
        [-3.1246],
        [-4.0194],
        [-4.9142]], grad_fn=<AddmmBackward0>)

In [55]:
loss = prediction - labels
loss_sum = loss.sum()
loss_sum.backward()

In [56]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step()
print(data.grad.item())

/var/folders/_s/b1dqc5_97sv5pf5lm7cdg5y80000gn/T/ipykernel_10505/3991422149.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1708025535489/work/build/aten/src/ATen/core/TensorBody.h:494.)
  print(data.grad.item())


AttributeError: 'NoneType' object has no attribute 'item'