In [22]:
import torch
import numpy as np

In [23]:
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
randM = torch.rand(5, 3)
randM

tensor([[0.4859, 0.1417, 0.5152],
        [0.4977, 0.5263, 0.2091],
        [0.2178, 0.1513, 0.5755],
        [0.4877, 0.7202, 0.5517],
        [0.6509, 0.6952, 0.0580]])

In [25]:
randM.shape

torch.Size([5, 3])

In [26]:
zeroM = torch.zeros(5, 3, dtype=torch.double)
zeroM

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [27]:
# view 改变矩阵维度
x = torch.randn(4, 4)
y = x.view(16)
y

tensor([ 0.5156, -0.6471,  0.3333,  0.8251,  0.2850, -2.3995, -1.5600,  0.4555,
        -0.4167, -0.7160, -0.5209, -0.5876,  0.6272,  0.2266, -0.3497, -1.8644])

In [28]:
z = x.view(-1, 8)
z

tensor([[ 0.5156, -0.6471,  0.3333,  0.8251,  0.2850, -2.3995, -1.5600,  0.4555],
        [-0.4167, -0.7160, -0.5209, -0.5876,  0.6272,  0.2266, -0.3497, -1.8644]])

In [29]:
# work with numpy

x = torch.randn(5, 3)
x_np = x.numpy()
x_np
x_np.shape

(5, 3)

In [38]:
# work with numpy

x_tensor = torch.from_numpy(np.ones((5, 3)))
x_tensor.size()

torch.Size([5, 3])