In [2]:
import torch

# 创建两个张量
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# 进行矩阵乘法
result = tensor1 @ tensor2

print(result)

tensor(32)


In [17]:
column1 = torch.ones(10, dtype=torch.float64)
column2 = torch.tensor([ i for i in range(10)], dtype=torch.float64)
column3 = torch.tensor([ i * i for i in range(10)], dtype=torch.float64)

In [19]:
column1

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)

In [11]:
column2

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [13]:
column3

tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=torch.float64)

In [18]:
sum = torch.cat([column1, column2, column3], dim = 1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [16]:
sum

tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,
         4.,  5.,  6.,  7.,  8.,  9.,  0.,  1.,  4.,  9., 16., 25., 36., 49.,
        64., 81.], dtype=torch.float64)